### PR TITLE
Fix writing and add category, strategys enums

### PR DESCRIPTION
**Pull request by miathedev**
The enums are usefull, if you want to do a full set of pagespeed tests.

With love,
Mia

### CODE REVIEW

**Comment by miathedev** [comment]
Never forget your own made commit automations. Thats why i needed so many commit/squashes.

**Comment by FirePing32** [comment]
@miathedev where have you implemented these enums ?

**Comment by miathedev** [comment]
PythonPSI/utils/strategy.py
PythonPSI/utils/category.py

**Comment by FirePing32** [comment]
@miathedev I mean where have you used these enums ? You have just declared them.

**Comment by miathedev** [comment]
I'm sorry for misunderstanding you.

Nothing yet public.
A self made yet to be done tool to scan websites for issues.
Basically like normal google pagespeed, but with the ability to save measurements to disk, e.g. excel.
Hopefully it helps me a lot in future.

Im basically doing sth like:
```
for strategy in Strategy:
        for category in Category:
          //... save to disk code
```

The enums are only useful if you want to automate things.

**Comment by FirePing32** [comment]
@miathedev So how are you planning to implement the save feature ? Like will it be only Excel, or maybe some kind of report generation of the pagespeed results ?

**Comment by miathedev** [comment]
Theres the audits field in lighthouseResult. Basically sth like:
```
audits = pagespeed_json["lighthouseResult"]["audits"]
for audit in audits:
    name = audits[audit]["id"]
    title = audits[audit]["title"]
    ...
    //To be done save to excel
```

(Draft)

Name as first row, title, numericValue, ... as secondary rows.
URL, Strategy and Category too of course.

I actually didnt think about report generation. With excel graphs it should be quite feasible. Good hint.

**Comment by miathedev** [comment]
To sum it up, the idea is to enable myself to simply track down if the performance of a site changed over time.

**Comment by FirePing32** [comment]
@miathedev Got it. Just tag me when you have implemented all the changes.

**Pull request closed without merging**
